name: Hourly ERCOT Collector

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        run: python collector.py --lookback 6

      - name: Commit updated data
        run: |
          if [[ -n "$(git status --porcelain data/ercot.parquet)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/ercot.parquet
            git commit -m "chore: update ERCOT data"
            git push
          else
            echo "No data changes detected"
          fi
